language: cpp
before_script:
- sudo apt-get install libboost-test-dev -y
- echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
- sudo apt-get update -qq
script:
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
deploy:
  provider: bintray
  skip_cleanup: true
  user: std307
  key: 
    secure: "DdNtSf7dJvC8gunm9XkSJF/CPR3u8m2Gu2A+sVKpnk990TSWtjh0adKytGaJtBnJOji5wJOiRTtqtVtl6W4JVwDSkIFro0sJJQenIbnlOx6JryXvcaJefDV/tlI7gWR3T6HZNImCzchOG8SqZXeZY3wfdzNJAmjw7PoQ7N5zsep7M0MblZEuj0o5k6AkYe0NIVdxUOuD+/zguIGsV9tOOtk7Oo+bpd6urvUHqgiOXEIqf9rguErLr857CzOV/i2EvwGnEWRG0fedmuM5oSluUE2lbd2QapM4Dv+TiliyqawwJBw1wt29gfxcF5GaK7CvHqHjiZf0caia3qhsFIsGAWX0mhT41MiKQ1+7j/2yjaFHDMPHmtgccCZSKJ627yRM7IfVftoh3AxhWAvHZzAe6HTADd8LRjYE4i+lmhIkEFNraD4MT7NVX8r6xcBjzMf9heOMECB4l8Pr5iupF2iA9zvmcn76e3FTJRCd88b7FMOpQlFiIWTDN1Z2Zk/PjnnYoL08ql0zMhk9yTQUEYNrX27unGjE+gxk4rcmR28epzgdRcNi3TD++gBev2yFsWCE1iT1nPENezR2aFmZsv8DWsdHywU0vceYfFbOdKQxr4/0EOG7gDkx4iwA5nlTg1sYU/rG4+AWrw8/wnZZWfg0VMystL3eWDCFh4zaxbMnGac="

  file: bintray-deploy-deb.js
  on:
    branch: homework1
  
