language: cpp
before_script:
- sudo apt-get install libboost-test-dev -y
- echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
- sudo apt-get update -qq
script:
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
deploy:
  provider: bintray
  skip_cleanup: true
  user: std307
  key: ${BINTRAY_API_KEY}
  file: bintray-deploy-deb.js
  on:
    branch: homework1
  
